name: Trigger Deploy Repo

on:
  push:
    branches:
      - main

jobs:
  dispatch:
    runs-on: ubuntu-latest

    steps:
      - name: Send repository_dispatch to Deploy repo
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: token ${{ secrets.DEPLOY_REPO_TOKEN }}" \
            -H "Content-Type: application/json" \
            https://api.github.com/repos/dndeepakitadmin/Learnages_Deploy/dispatches \
            -d '{"event_type":"ai-studio-update"}'
